/* Generated by Babel */
/*jshint esversion: 6*/
/*global $, document, Image, window, setTimeout, setInterval, clearInterval*/

"use strict";

$("#contact-form").submit(submitForm);

function submitForm(e) {
    e.preventDefault();

    var $form = $(this);
    var formAction = $form.attr("action");

    $.post(formAction, $form.serialize(), function (response) {
        $(".contact-form__submit").fadeTo(300, 0, function () {
            $(".contact-form__submit").replaceWith(response);
            $form.trigger("reset").find(":input").prop("disabled", true).addClass("form--is-disabled");
        });
    });
}